- name: Check if apt-cache is available
  shell: command -v apt-cache
  failed_when: no
  changed_when: no
  register: apt_cache

- name: Fail if apt_cache is not available
  fail:
    msg: "apt-cache is not available on current system, cannot install zsh"
  when: apt_cache.rc != 0

- name: Get available zsh version
  shell: apt-cache madison zsh | cut -d\| -f2 | sort | tail -1 | xargs
  register: zsh_versions

- name: Fail if zsh is too old
  fail:
    msg: "A minimum zsh 5.1 must be available for installation. Zsh version available on current system: {{ zsh_versions.stdout_lines[0] }}"
  when: zsh_versions.stdout_lines[0] < "5.1"


- name: Make sure zsh is installed
  package:
    name: zsh
    state: present
  become_method: sudo
  become: yes

- name: Check if .oh-my-zsh already exists
  stat: path="{{ ansible_env.HOME }}/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Download oh-my-zsh install script
  get_url: 
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    mode: 0755
    dest: /tmp/
  when: oh_my_zsh_stat.stat.exists==false

- name: Execute oh-my-zsh install script
  shell: /tmp/install.sh
  when: oh_my_zsh_stat.stat.exists==false

- name: Delete oh-my-zsh install script
  file:
    dest: "/tmp/install.sh"
    state: absent
  when: oh_my_zsh_stat.stat.exists==false

- name: Configure theme in .zshrc
  replace:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: 'ZSH_THEME=.*$'
    replace: 'ZSH_THEME="powerlevel10k/powerlevel10k"'

- name: Configure plugins in .zshrc
  replace:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: 'plugins=.*$'
    replace: 'plugins=(git vagrant vagrant-prompt)'


- name: Configure .zshrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      [[ -f ~/.zshrc_local ]] && source ~/.zshrc_local
      # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
      [[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

      ZSH_DISABLE_COMPFIX=true

- name: Create host-specific (local) zsh settings
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc_local"
    line: "DEFAULT_USER={{ ansible_env.USER }}"
    create: yes

- block:

  - name: Check if powerlevel10k already exists
    stat: path="{{ p10k_path }}"
    register: p10k_stat

  - name: Install powerlevel10k
    git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: "{{ p10k_path }}"
      depth: 1
    when: p10k_stat.stat.exists==false

  - name: Install powerlevel10k config
    file:
      src: "{{ dotfiles_home }}/roles/zsh/files/.p10k.zsh"
      dest: "{{ ansible_env.HOME }}/.p10k.zsh"
      state: link
    when: p10k_stat.stat.exists==false

  vars:
    p10k_path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
