- name: Get available zsh version
  shell: apt-cache madison zsh | cut -d\| -f2 | sort | tail -1 | xargs
  register: zsh_versions

- name: Fail if zsh is too old
  fail:
    msg: "A minimum zsh 5.1 must be available for installation. Zsh version available on current system: {{ zsh_versions.stdout_lines[0] }}"
  when: zsh_versions.stdout_lines[0] < "5.1"


- name: Make sure zsh is installed
  package:
    name: zsh
    state: present
  become_method: sudo
  become: yes

- name: Check if .oh-my-zsh already exists
  stat: path="{{ ansible_env.HOME }}/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Download oh-my-zsh install script
  get_url: 
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    mode: 0755
    dest: /tmp/
  when: oh_my_zsh_stat.stat.exists==false

- name: Execute oh-my-zsh install script
  shell: /tmp/install.sh
  when: oh_my_zsh_stat.stat.exists==false

- name: Delete oh-my-zsh install script
  file:
    dest: "/tmp/install.sh"
    state: absent
  when: oh_my_zsh_stat.stat.exists==false
