- name: Install terminator
  package: name=terminator state=present
  become_method: sudo
  become: yes

- name: Install font
  copy:
    src: FiraCodeNerdFont-Regular.ttf
    dest: /usr/local/share/fonts/
  become_method: sudo
  become: yes

- name: Refresh font cache
  import_role: 
    name: common
    tasks_from: font-cache.yml
  vars:
    font: FiraCode Nerd Font Regular

- block:
  - name: Make sure path exists
    file:
      dest: "{{ conf_path }}"
      state: directory
  - name: Link terminator config
    file:
      src: "{{ role_path }}/files/config"
      dest: "{{ conf_path }}/config"
      state: link
  vars:
    conf_path: "{{ ansible_env.HOME }}/.config/terminator"


- name: Add terminator to Gnome Favorites (Dock)
  gnome_favorites.py:
    app: 'terminator.desktop'
