- name: Install terminator
  package: name=terminator state=present
  become_method: sudo
  become: yes

- name: Install font
  get_url: 
    url: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete%20Mono.ttf
    mode: 0644
    owner: root
    group: root
    dest: /usr/local/share/fonts
  become: yes

- name: Refresh font cache
  import_role: 
    name: common
    tasks_from: font-cache.yml
  vars:
    font: FuraCode Nerd Font Mono

- block:
  - name: Make sure path exists
    file:
      dest: "{{ conf_path }}"
      state: directory
  - name: Link terminator config
    file:
      src: "{{ role_path }}/files/config"
      dest: "{{ conf_path }}/config"
      state: link
  vars:
    conf_path: "{{ ansible_env.HOME }}/.config/terminator"


- name: Add terminator to Gnome Favorites (Dock)
  gnome_favorites.py:
    app: 'terminator.desktop'
