- name: Install tools via apt
  package:
    name:
     - iftop
     - bat
    state: present
  become_method: sudo
  become: yes

- name: Install pip
  package:
    name:
     - python3-pip
    state: present
  become_method: sudo
  become: yes

- name: Install python tools and libraries
  pip:
    executable: pip3
    name:
     - bpytop
     - github3.py
  become_method: sudo
  become: yes

- name: Link bat to batcat
  file:
    src: "/usr/bin/batcat"
    dest: "/usr/bin/bat"
    state: link
  when: ansible_os_family == 'Debian'
  become_method: sudo
  become: yes

- name: Get the latest release of moar
  community.general.github_release:
    user: walles
    repo: moar
    action: latest_release
  register: moar_release

- name: Download moar {{ moar_release.tag }}
  get_url: 
    url: "https://github.com/walles/moar/releases/download/{{ moar_release.tag }}/moar-{{ moar_release.tag }}-linux-386"
    dest: /usr/local/bin/moar
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  become_method: sudo
  become: yes

- name: Add tool settings to .profile
  blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    block: |
      export MANPAGER="sh -c 'col -bx | bat -l man -p'"
      export BAT_THEME="Visual Studio Dark+"
      export PAGER=/usr/local/bin/moar
      export BAT_PAGER='/usr/local/bin/moar -no-linenumbers'
