- name: Install tools via apt
  package:
    name:
     - iftop
     - bat
    state: present
  become_method: sudo
  become: yes

- name: Install pip
  package:
    name:
     - python3-pip
    state: present
  become_method: sudo
  become: yes


- name: Install python tools
  pip:
    executable: pip3
    name:
     - bpytop
  become_method: sudo
  become: yes

- name: Link bat to batcat
  file:
    src: "/usr/bin/batcat"
    dest: "/usr/bin/bat"
    state: link
  when: ansible_os_family == 'Debian'
  become_method: sudo
  become: yes

- name: Set bat color theme and make it man page viewer
  lineinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    line: "{{ item }}"
  with_items:    
    - "export MANPAGER=\"sh -c 'col -bx | bat -l man -p'\""
    - "export BAT_THEME=\"Visual Studio Dark+\""
  