- name: Install prerequisites
  package:
    name:
     - gawk
     - m4
     - libglib2.0-dev
     - libwxgtk3.0-dev
     - libssh-dev
     - libssl-dev
     - libsmbclient-dev
     - libnfs-dev
     - libneon27-dev
     - cmake
     - g++
    state: present
  become_method: sudo
  become: yes

- name: Download far2l sources
  git:
    repo: https://github.com/elfmz/far2l
    dest: "/usr/local/src/far2l"
    depth: 1
  become_method: sudo
  become: yes
  register: source_update

- name: Create build directory
  file:
    path: "/usr/local/src/far2l/build"
    state: directory
  become_method: sudo
  become: yes

- name: Create makefiles
  shell: "cmake -DUSEWX=yes -DCMAKE_BUILD_TYPE=Release .."
  args:
    chdir: "/usr/local/src/far2l/build"
  become_method: sudo
  become: yes
  when: source_update.changed

- name: Build
  shell: "make -j{{ ansible_processor_vcpus }}"
  args:
    chdir: "/usr/local/src/far2l/build"
  become_method: sudo
  become: yes
  when: source_update.changed

- name: Install
  shell: "make install"
  args:
    chdir: "/usr/local/src/far2l/build"
  become_method: sudo
  become: yes
  when: source_update.changed

- name: Add far to Gnome Favorites (Dock)
  gnome_favorites.py:
    app: 'far2l.desktop'

- name: Install font
  copy:
    src: TerminalVector.ttf
    dest: /usr/local/share/fonts/
  become_method: sudo
  become: yes

- name: Refresh font cache
  import_role: 
    name: common
    tasks_from: font-cache.yml
  vars:
    font: TerminalVector

- name: Ensure configure dir is present
  file:
    path: "{{ ansible_env.HOME }}/.config/far2l/"
    state: directory
    recurse: yes

- name: Configure font
  file:
    src: "{{ role_path }}/files/font"
    dest: "{{ ansible_env.HOME }}/.config/far2l/font"
    state: link
