- name: Add far2l ppa
  apt_repository:
    repo: ppa:far2l-team/ppa
  when: ansible_os_family == 'Debian'
  become_method: sudo
  become: yes

- name: Install far2l
  package:
    name: far2l
    state: present
  when: ansible_os_family == 'Debian'
  become_method: sudo
  become: yes

- name: Install jumpword far2l plugin
  vars:
    build_path: "/tmp/far2l-sources"
  block:
    - name: Install prerequisites
      package:
        name:
        - gawk
        - m4
        - cmake
        - g++
        - pkg-config
        - libuchardet-dev
        - libxerces-c-dev
        - libspdlog-dev
        state: present
      become_method: sudo
      become: yes

    - name: Download far2l sources
      git:
        repo: https://github.com/elfmz/far2l
        dest: "{{ build_path }}"
        depth: 1
        force: true

    - name: Download jumpword sources
      git:
        repo: https://github.com/axxie/far2l-jumpword.git
        dest: "{{ build_path }}/jumpword"
        version: main
        depth: 1

    - name: Add jumpword to far2l CMakeLists.txt
      lineinfile:
        path: "{{ build_path }}/CMakeLists.txt"
        line: "add_subdirectory(jumpword)"

    - name: Create build directory
      file:
        path: "{{ build_path }}/build"
        state: directory

    - name: Create makefiles
      shell: "cmake -DUSEWX=no -DCMAKE_BUILD_TYPE=Release .."
      args:
        chdir: "{{ build_path }}/build"
      register: cmake_output        
      changed_when: "'The C compiler identification is' in cmake_output.stdout"
      
    - name: Build
      shell: "make -j{{ ansible_processor_vcpus }} jumpword"
      args:
        chdir: "{{ build_path }}/build"
      register: build_output
      changed_when: "'jumpword.far-plug-wide' in build_output.stdout"        

    - name: Install
      copy:
        remote_src: true
        src: "{{ build_path }}/build/install/Plugins/jumpword/plug"
        dest: "/usr/lib/far2l/Plugins/jumpword/"
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      become_method: sudo
      become: yes

- name: Add far to Gnome Favorites (Dock)
  gnome_favorites.py:
    app: 'far2l.desktop'

- name: Install font
  copy:
    src: font/TerminalVector.ttf
    dest: /usr/local/share/fonts/
  become_method: sudo
  become: yes

- name: Refresh font cache
  import_role: 
    name: common
    tasks_from: font-cache.yml
  vars:
    font: TerminalVector

- name: Ensure configure dirs are present
  file:
    path: "{{ ansible_env.HOME }}/.config/far2l/{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - settings
    - plugins

- name: Link settings
  file:
    src: "{{ role_path }}/files/.config/far2l/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/far2l/{{ item }}"
    state: link
  with_items:
    - font
    - palette.ini
    - settings/config.ini
    - settings/key_macros.ini
    - plugins/align
    - plugins/colorer

- name: Configure folder shortcut
  template:
    src: ./templates/bookmarks.ini
    dest: "{{ ansible_env.HOME }}/.config/far2l/settings/bookmarks.ini"

- name: Link colorer scheme
  file:
    src: "{{ role_path }}/files/colorer-hrd/axxie.hrd"
    dest: "/usr/lib/far2l/Plugins/colorer/base/hrd/console/axxie.hrd"
    state: link
  when: ansible_os_family == 'Debian'
  become_method: sudo
  become: yes

- name: Configure color scheme
  blockinfile:
    path: "/usr/lib/far2l/Plugins/colorer/base/hrd/catalog-console.xml"
    block: |
      <hrd class="console" name="Axxie" description="Axxie">
        <location link="&hrd;/console/axxie.hrd"/>
      </hrd>
  when: ansible_os_family == 'Debian'
  become_method: sudo
  become: yes

- name: Disable Gnome shortcuts
  gsetting.py:
    path: org.gnome.desktop.wm.keybindings
    key: "{{ item }}"
    value: "['disabled']"
  with_items:
    - panel-main-menu
    - panel-run-dialog
    - switch-to-workspace-down
    - switch-to-workspace-up
    - cycle-group-backward
    - begin-move
    - toggle-maximized
    - begin-resize
    - cycle-group
