- name: Install prerequisites
  package:
    name:
     - gawk
     - m4
     - libglib2.0-dev
     - libwxgtk3.0-dev
     - libssh-dev
     - libssl-dev
     - libsmbclient-dev
     - libnfs-dev
     - libneon27-dev
     - cmake
     - g++
     - libpcre2-dev
     - libxerces-c-dev
     - libspdlog-dev
     - libuchardet-dev
     - libarchive-dev
    state: present
  become_method: sudo
  become: yes

- name: Download far2l sources
  git:
    repo: https://github.com/elfmz/far2l
    dest: "/usr/local/src/far2l"
    depth: 1
  become_method: sudo
  become: yes
  register: source_update

- name: Create build directory
  file:
    path: "/usr/local/src/far2l/build"
    state: directory
  become_method: sudo
  become: yes

- name: Create makefiles
  shell: "cmake -DUSEWX=yes -DCMAKE_BUILD_TYPE=Release .."
  args:
    chdir: "/usr/local/src/far2l/build"
  become_method: sudo
  become: yes
  when: source_update.changed

- name: Build
  shell: "make -j{{ ansible_processor_vcpus }}"
  args:
    chdir: "/usr/local/src/far2l/build"
  become_method: sudo
  become: yes
  when: source_update.changed

- name: Install
  shell: "make install"
  args:
    chdir: "/usr/local/src/far2l/build"
  become_method: sudo
  become: yes
  when: source_update.changed

- name: Add far to Gnome Favorites (Dock)
  gnome_favorites.py:
    app: 'far2l.desktop'

- name: Install font
  copy:
    src: font/TerminalVector.ttf
    dest: /usr/local/share/fonts/
  become_method: sudo
  become: yes

- name: Refresh font cache
  import_role: 
    name: common
    tasks_from: font-cache.yml
  vars:
    font: TerminalVector

- name: Ensure configure dirs are present
  file:
    path: "{{ ansible_env.HOME }}/.config/far2l/REG"
    state: directory
    recurse: yes

- name: Link font and palette
  file:
    src: "{{ role_path }}/files/.config/far2l/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/far2l/{{ item }}"
    state: link
  with_items:
    - font
    - palette.ini

- name: Link registry settings
  file:
    src: "{{ role_path }}/files/.config/far2l/REG/HKU"
    dest: "{{ ansible_env.HOME }}/.config/far2l/REG/HKU"
    state: link

- name: Create folder for folder shortcuts
  file:
    path: "{{ansible_env.HOME }}/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-FolderShortcuts"
    state: directory

- name: Configure folder shortcut
  template:
    src: ./templates/v-Shortcut1
    dest: "{{ ansible_env.HOME }}/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-FolderShortcuts/v-Shortcut1"

- name: Link colorer scheme
  file:
    src: "{{ role_path }}/files/colorer-hrd/axxie.hrd"
    dest: "/usr/local/share/far2l/Plugins/colorer/base/hrd/console/axxie.hrd"
    state: link
  become_method: sudo
  become: yes

- name: Configure color scheme
  blockinfile:
    path: "/usr/local/share/far2l/Plugins/colorer/base/hrd/catalog-console.xml"
    block: |
      <hrd class="console" name="Axxie" description="Axxie">
        <location link="&hrd;/console/axxie.hrd"/>
      </hrd>
  become_method: sudo
  become: yes

- name: Disable Gnome shortcuts
  gsetting.py:
    path: org.gnome.desktop.wm.keybindings
    key: "{{ item }}"
    value: "['disabled']"
  with_items:
    - panel-main-menu
    - panel-run-dialog
    - switch-to-workspace-down
    - switch-to-workspace-up
    - cycle-group-backward
    - begin-move
    - toggle-maximized
    - begin-resize
    - cycle-group
